name: FacCore
depend: [Libraries]
version: '-1'
main: fr.entasia.faccore.Main
api-version: '1.15'
commands:
  faccore:

  setspawn:

  masteredit:
    aliases: [buildtoggle]

  fadmin:
    aliases: [facadmin]


  bin:
    aliases: [corbeille, poubelle, trash, binaries]

  spawn:

  f:
    aliases: [fac, faction, factions]

  rank:


  money:
    aliases: [monnaie, bal, balance]

  eco:
    aliases: [economy, economie]

  baltop:

  pay:
